on: [push]

jobs:
  docker-build-job:
    runs-on: ubuntu-latest
    name: A job to ensure binaries build
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Binary  
      uses: ./docker-build-binary-action

